name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install && cd frontend && npm install
      - name: Check style
        run: npm run lint
      - name: Frontend test
        run: cd frontend && npm run test
      - name: Build
        run: npm run build:ui
      - uses: JorgeLNJunior/render-deploy@v1.3.2
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
          api_key: ${{ secrets.RENDER_API_KEY }} # required
          clear_cache: false # Clear build cache. Optional
          wait_deploy: false # Wait until the deploy status is successful. Warning! Free Render services can take +5 minutes to be fully deployed. Optional
